### ISSUE TITLE
Internet? Minecraft? noch nie gehört...

### ISSUE THREAD

**Issue by sophkaka** [FuerthCraft/fuerthcraft#10]
### Minecraft Version

Unbekannt

### Minecraft Client

Keines der gelisteten

### Was ist passiert?

was ist Minecraft? LG Marianne

### Wie können wir den Bug reproduzieren?

Was ist dieses Sozial Media von dem immer alle reden?

### Weitere Informationen

ich verkaufe grbauchtes Toilettenpapier, bei Interesse gerne melden :)

**Comment by pigupp** [comment]
ok
